import { Button, Flex } from '@chakra-ui/react';
import Head from 'next/head';
import Link from 'next/link';
import { ChatAI } from '@/features/chat/components/ChatAi';

export default function Home() {
  return (
    <>
      <Head>
        <title>Daily Anki</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Flex direction='column' align='center'>
          <ChatAI chatType='begin' />
          <Link href='/deck'>
            <Button>Start</Button>
          </Link>
          {/* <Link href='/chat'>
            <Button>Start</Button>
          </Link> */}
        </Flex>
      </main>
    </>
  );
}
